---
title: 双选择 oddball 任务数据分析：基于 R
author: Ginger Yu
date: '2021-08-26'
slug: DAoddball
categories:
  - Research
tags:
  - Two Choic Oddball
draft: # yes
---

> 不打无准备的仗

# 引言

因为疫情原因，没有收集数据。但是研究的进度不能耽误。就想到利用预实验的数据提前写好数据分析程序。

这样做有以下几点合理性：

- R 数据分析是代码形式的分析，可重复利用；
- 预实验数据在内容和排列方式上与正式实验一致，写好后，可以直接用在正式实验数据上；

有以下几点优势：

- 根据数据分析情况，可适时调整实验程序收集的数据格式和项目；可编辑；
- 收数据时，可以立马导入，查看结果；响应速度快；
- 可以此判断变量的数量和内容，即收集哪些变量。

因此，准备花两天时间把代码写出来，并在博客中记录经验。

# 材料

被试间平衡反应方式与刺激类型的对应关系；

反应时代价和准确率代价为分析指标，代价越小，行为抑制控制能力越强。

2 × 2 区组实验设计（被试内）

组间变量是`Type`，组内变量是`SessionNumber`。前者指被试分组，后者指前后测。

采用重复测量方差分析，检验前后测差异，以及两组被试间的差异。

重复测量方差分析的基本假设是正态性和方差齐性，需要在方差分析前进行检验。

# 加载包

```r
library(tidyverse)
```

# 导入数据

按照被试编号（主）、实验序号（次）、试次（再次）进行排序
```r
oddballfiles <- list.files(path = "~/GitHub/Station/exp_TwoChoice_oddball_xiaoyu/TwoChoice_oddball_Data/", pattern = ".csv", full.names = TRUE)
data_oddball <- map_df(oddballfiles, read_csv)
```

被试类型应该单独一个文件，几个任务数据共用

```r
participant_type <- read_csv("~/GitHub/Station/exp_TwoChoice_oddball_xiaoyu/ParticipantType/ParticipantType.csv")
```

# 预处理

提取正式实验数据

```r
oddball_filted <- data_oddball %>% filter(is.na(PracticeNum) == TRUE)
```

剔除反应时低于 300 ms 的试次

```r
oddball_filted <- oddball_filted %>% filter(RT > 0.300)
```

剔除反应时大于 3000 的试次

```r
oddball_filted <- oddball_filted %>% filter(RT < 3.000)
```

计算每个被试的平均反应时和准确率

```r
oddball_ave <- oddball_filted %>%
  group_by(ParticipantID, SessionNumber, WordNum) %>%
  summarise(
    RT = mean(RT),
    ACC = mean(ACC),
    .groups = "drop"
  )
```

计算反应时代价和准确率代价

```r
oddball_wide <- oddball_ave %>%
  pivot_wider(
    names_from = WordNum,
    values_from = c(RT, ACC)
  )
```


```r
oddball_cost <- oddball_wide %>%
  transmute(
    ParticipantID = ParticipantID,
    SessionNumber = SessionNumber,
    RT_cost = 1000 * (RT_2 - RT_1),
    ACC_cost = ACC_1 - ACC_2
  )
```

增加被试类型信息

```r
oddball_cost <- oddball_cost %>% left_join(., participant_type, by = "ParticipantID")
```

# 重复测量方差分析

方差分析有

- 单因素组间方差分析
- 单因素组内方差分析（重复测量）
- 含组间和组内因子的双因素方差分析（混合模型方差）

也可以按照是否区组设设计

- 完全随机设计（因素组间方差分析）
- 随机区组设计（混合模型方差分析）

我们在这里进行的是混合模型方差分析。表达式为：

```
# 单个组内因子（W）
# 单个组间因子（B）
aov(y ~ B + W + Error(Subject / W), data = DATA)
```

方差齐次性检验


重复测量方差分析

```r
# 反应时代价
oddball_rt_aov <- oddball_cost %>%
  aov(RT_cost ~ Type * SessionNumber + Error(ParticipantID / SessionNumber), data =  .)
oddball_rt_aov %>% summary()
```

```r
# 准确率代价
oddball_acc_aov <- oddball_cost %>%
  aov(ACC_cost ~ Type * SessionNumber + Error(ParticipantID / SessionNumber), data =  .)
oddball_acc_aov %>% summary()
```

结果解读

- Type 对 反应时代价的影响；
- 控制 Type 是，反应时代价的前后测差异；
- 控制两因素主效应时，组别和时间的交互效应。

事后检验

# 描述性统计

既反映总体平均值大小，又反映被试分布。还有置信区间（误差bar）

计算均值和标准差

# 可视化

折线图：展示交互作用

```r
# 反应时代价
with(oddball_cost,
  interaction.plot(Type, SessionNumber, RT_cost,
    type = "b", col = c("red", "blue"), pch = c(16, 18),
    main = "Interaction plot",
    ylab = "RT Cost (ms)")
  )
```

```r
# 准确率代价
with(oddball_cost,
  interaction.plot(Type, SessionNumber, ACC_cost,
    type = "b", col = c("red", "blue"), pch = c(16, 18),
    main = "时间与分组的交互作用图",
    ylab = "ACC Cost")
  )
```

箱线图

```r
# 反应时代价
oddball_cost %>% boxplot(RT_cost ~ Type * SessionNumber,
  data = .,
  col = c("red", "green"),
  main = "箱线图：反应时代价",
  ylab = "RT Cost (ms)")
```
